eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    instance:
      preferIpAddress: true
server:
  context-path: /
  error:
    whitelabel:
      enabled: false
  port: 8001
spring:
  application:
    name: weather-data-server
