server:
  port: 8001
  error:
    whitelabel:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    instance:
      preferIpAddress: true

spring:
  application:
    name: weather-data-server