server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: @pom.artifactId@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dragonflyflyfly/springcloud-demo/ #配置git仓库的地址
          searchPaths: config-repo #仓库路径下的相对搜索位置，可以配置多个
          username: '' #访问git仓库的用户名
          password: '' #访问git仓库的密码
