server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 30000 #30s。仅开发测试阶段用，生产环境使用默认值
  client:
    registerWithEureka: false #自身就是eureka，不需要将自己注册到Eureka。默认true,会注册自身。
    fetchRegistry: false #单点，不需要从Eureka获取注册信息。默认true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #与eureka交互的地址。查询和注册服务都需要该地址。
  instance:
    hostname: discovery #该服务注册中心的hostname

