server:
  port: 6001

spring:
  application:
    name: @pom.artifactId@
  cloud:
    client:
      ipAddress: 127.0.0.1 #ip地址

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    instance:
      preferIpAddress: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}